image: node

before_script:
  - node --version
  - npm --version
  - npm ci || npm install

test:
  script:
    - npm run make

pages:
  stage: deploy
  script:
    - npm run make
  environment:
    name: Production
    url: https://react-bootstrap-example.tripetto.com/
  artifacts:
    paths:
      - static
  only:
    - master
